### ISSUE TITLE
DOCKER_BUILDKIT requirement.

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-application-server#16]
Followed the instructions to get WAS and with the "build" received this message:
Step 4/8 : RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

I did the:
bert@ubuntu-willow:~/willow-application-server$ sudo DOCKER_BUILDKIT=1 docker build .
[+] Building 40.2s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                0.1s
 => => transferring dockerfile: 252B                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                   0.1s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/python:3.11.4-slim-bookworm                                                                                      0.0s
 => [internal] load build context                                                                                                                                   0.2s
 => => transferring context: 238.39kB                                                                                                                               0.0s
 => [stage-0 1/5] FROM docker.io/library/python:3.11.4-slim-bookworm                                                                                                0.4s
 => [stage-0 2/5] WORKDIR /app                                                                                                                                      0.1s
 => [stage-0 3/5] COPY requirements.txt .                                                                                                                           0.1s
 => [stage-0 4/5] RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt                                                                       35.6s
 => [stage-0 5/5] COPY . .                                                                                                                                          0.2s
 => exporting to image                                                                                                                                              3.6s
 => => exporting layers                                                                                                                                             3.6s
 => => writing image sha256:ba9622daee85ebe568e86ed098b9b83a0217883e12663035f5cd284b6ead2b1a      

But  when I tried to run the ./utils.sh build - I got the same error message:
bert@ubuntu-willow:~/willow-application-server$ sudo ./utils.sh build
Using configuration overrides from .env file
WAS IP is 192.168.1.210
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11807  100 11807    0     0  67806      0 --:--:-- --:--:-- --:--:-- 67468
Sending build context to Docker daemon  290.3kB
Step 1/8 : FROM python:3.11.4-slim-bookworm
 ---> be2470db10f7
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 27388a12e556
Step 3/8 : COPY requirements.txt .
 ---> Using cache
 ---> a5257dcd5a13
Step 4/8 : RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

Where do I go from here? What am I missing?

**Comment by bert269** [comment]
LOVE IT!

I could not do the build from scratch (as above) - but I did the docker run and flashed all the ESP_BOXes (and one-lite) I have.
Really, truley LOVE this - it is SO much easier.
I think we are ready for Home Assistant integration!

THANK you!

**Comment by bert269** [comment]
I ran this command, and not it seems that the build went a little further:
![image](https://github.com/toverainc/willow-application-server/assets/18601216/46e9447d-3fb7-458d-bc7a-ec80e38d798f)

**Comment by kristiankielhofner** [comment]
DOCKER_BUILDKIT is a pretty standard and reasonable requirement for anywhere near recent docker installations - it's been the default in docker for quite some time.
