### ISSUE TITLE
This is more of a question, not an issue.

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-application-server#18]
What happens on this screen when I click on "Save and Apply"?
![image](https://github.com/toverainc/willow-application-server/assets/18601216/133f35a8-79a8-4934-8e15-4565cd5b9979)

Does it send these details to all the connected clients?

The reason why I ask is that I have two network routers in my house - due to distance. They are both on the same network, but have different access-point names, to ensure a stronger signal.
If this would send thess details to all the connected willow clients, it means that I will have to redo the settings for the clients that is not accessed by this router.

**Comment by kristiankielhofner** [comment]
We don't currently support setting different SSIDs for different devices within the same managed install.

Is there a particular reason you don't set your access points to the same SSID and PSK and let them select the appropriate access point? Just trying to better understand your particular use case...

**Comment by bert269** [comment]
Yes, distance from the access points. I have one in my office in the front of the house and one in the living room. Two ESP-BOXs are close to each of the access points and far from the other.
Although the Wi-fi settings are set in the configuration settings, I noticed on the final 'Flash' page it can be set/changed again. Will this override the values from the configuration settings, during the flash? This is what I have been using to distinguish between the two access points.

**Comment by stintel** [comment]
As @kristiankielhofner mentioned, we currently only really support using the same settings for all Willow instances. You can work around it by changing the settings, click _Save_ instead of _Save and Apply_, then in the _Clients_ tab, use _Apply NVS_ to apply to the one you need.

**Comment by bert269** [comment]
Perfect, that is what I thought and how I did it so far.
Thanks

**Comment by kristiankielhofner** [comment]
The good news is because Wifi is configured, stored, and saved separately from everything else you can jump through this once to onboard them and use the other configuration settings as you normally would. Of course works for OTA as well.
