### ISSUE TITLE
moved WAS to another server.

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-application-server#19]
Hi, I stopped the WAS that was running in my test environment and moved it to the same server I am running WIS on.

I can flash the devices via the web interface to the new WAS deployment, but the devices does not show up now under "clients" anymore. What am I missing?

**Comment by bert269** [comment]
not to worry....it took about 10minutes to find the first device. A little slow but it's working.
Issue will be closed.
I assume it is not a problem running WAS on the same device as WIS?
It's an AMD CPU 4170, 16GB RAM and a 1080ti(for wis).
CPU is running less than 10% busy.

**Comment by nikito** [comment]
I have everything running on the same docker server as well with similar specs, that should not be a problem. The delay in detection may just be network related. I tested quick with one of my devices by restarting it, and it disappeared in a few seconds and reappeared a few seconds later when I refreshed. :)

**Comment by bert269** [comment]
Thank you.
