### ISSUE TITLE
Can WAS not be installed on arm64?

### ISSUE THREAD

**Issue by nerlins** [toverainc/willow-application-server#22]
It would be preferable for me to install WAS on a little Ubuntu Mate Pi4 server I have. When I run the docker command it barks that the architecture doesn't match amd64, and the container exits. Is there any way I can get this on here, or do I absolutely need it running on an amd64 machine?

**Comment by stintel** [comment]
Can you try the command below and let us know if it works for you?

```
docker run --detach --name=willow-application-server --pull=always --network=host --restart=unless-stopped --volume=was-storage:/app/storage ghcr.io/toverainc/willow-application-server:improvements
```

**Comment by stintel** [comment]
@kristiankielhofner discovered this is still not enough to run on Raspberry Pi OS with 64 bit kernel and 32 bit userspace. Unfortunately it is non-trivial to build WAS for 32 bit ARM userspace, as there don't seem to be any numpy wheels available for that. We're sure it can be done, but right now we have other priorities, so if you run in the following error we suggest to switch to either build yourself or switch to a full 64 bit OS:

```
docker: no matching manifest for linux/arm/v8 in the manifest list entries.
```

**Comment by nerlins** [comment]
> Can you try the command below and let us know if it works for you?
> 
> ```
> docker run --detach --name=willow-application-server --pull=always --network=host --restart=unless-stopped --volume=was-storage:/app/storage ghcr.io/toverainc/willow-application-server:improvements
> ```
> 
> 

I didn't realize this got close so quickly. I haven't had a chance to log back in. My OS is 64-bit, so you think it would work? I'm going to try it this evening.

**Comment by kristiankielhofner** [comment]
Yes, arm64 works (tested on Raspberry Pi 4 and Nvidia Jetson).

**Comment by nerlins** [comment]
> Yes, arm64 works (tested on Raspberry Pi 4 and Nvidia Jetson) as long as you're using a 64 bit OS.

It's working. 👍
