### ISSUE TITLE
Single ESP box appears to be getting duplicated

### ISSUE THREAD

**Issue by nikito** [toverainc/willow-application-server#3]
When flashing the WAS willow build onto the ESP box, I am seeing that it is getting duplicated in WAS:
![image](https://github.com/toverainc/willow-application-server/assets/733609/50f5f63c-f79e-4c75-abde-502e1a1931a9)

Additionally seems to be issues in the log, and the unit is stuck in a loop. I'm attaching a log export for reference from the ESP box with full debug enabled. 😃 
[willow-was-log.txt](https://github.com/toverainc/willow-application-server/files/11868148/willow-was-log.txt)

Note if this is due to things not yet being ready for WAS please let me know, wasn't sure if I was testing prematurely 😆

**Comment by kristiankielhofner** [comment]
In the wasng branch WAS makes sure the client devices returned via API are unique by MAC.
