### ISSUE TITLE
Streamlit app not starting - Docker container

### ISSUE THREAD

**Issue by Leticron** [toverainc/willow-application-server#35]
I encounter the same problem when building the WAS dockerfile myself or using the docker command 
` docker run --detach --name=willow-application-server --pull=always --network=host --restart=unless-stopped --volume=was-storage:/app/storage ghcr.io/toverainc/willow-application-server:main
`
After visiting the streamlit app under the host ip the app provides the following error:

`AttributeError: 'list' object has no attribute 'get'`

Traceback within Streamlit app:
`File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/app/ui.py", line 59, in <module>
    latest_release = get_release_gh_latest()
                     ^^^^^^^^^^^^^^^^^^^^^^^
File "/app/shared/was.py", line 153, in get_release_gh_latest
    if json.get('tag_name'):
       ^^^^^^^^`

Any ideas where to start here?

**Comment by kristiankielhofner** [comment]
This was fixed on the API side a while ago, you shouldn't have seen this as of the time you created the issue.

Worst case, can you restart WAS and try again?

**Comment by kristiankielhofner** [comment]
For the next stable release series of Willow (0.2x) we have a completely new Web UI - streamlit is terrible and was always more of a placeholder to get dynamic config, updates, etc out and available. This comes with a redesigned WAS backend. In implementing this we introduced a regression on the hosted API side for getting current releases, which caused your issue (we caught it hours before you created it). The new UI and WAS always refreshes live in the UI so releases are immediately available and the UI, WAS, etc don't maintain state.

Current WAS and WAS UI does maintain state all over the place and that's likely what was happening here.

**Comment by Leticron** [comment]
Sounds great - I will close the issue then.
