### ISSUE TITLE
MQTT as Endpoint 

### ISSUE THREAD

**Issue by longunmin** [toverainc/willow-application-server#45]
Would it be possible to have an MQTT endpoint be an option, instead of Home Assistant or REST?

**Comment by stintel** [comment]
Moved the issue as we will implement this in WAS.

**Comment by longunmin** [comment]
> So I started on an MQTT endpoint for WAS: [63fa17c](https://github.com/toverainc/willow-application-server/commit/63fa17c5f21dc32a196259bde68120b42001e92d)
> 
> If you want to test it you could use this container image: ghcr.io/toverainc/willow-application-server:feature-mqtt_endpoint. As this does not include the [UI](https://github.com/toverainc/willow-application-server-ui), you'll have to run it yourself.

Thanks! This is amazing! Great work
