### ISSUE TITLE
Saving NVS while testing connection leaves a persistent WS connection on WAS

### ISSUE THREAD

**Issue by nikito** [toverainc/willow-application-server#9]
With latest pull, when I save nvs config and it tests the websocket connection, it never closed the connection. As a result the client connections goes up and never goes down. For instance I have 2 esp boxes connected, and after saving 5 times my connections count shows as 7 and is remaining there even after refreshes.

**Comment by stintel** [comment]
Good catch. I was wondering where that came from. Should be fixed in feature/was_url. As this is an issue in a feature branch, and commit introducing the bug has been fixed up, a fixes tag in the commit message makes no sense. May I kindly ask you to close this issue if it is fixed for you?

**Comment by nikito** [comment]
Confirmed it is fixed now in feature/was_url!
